### ISSUE TITLE
Can we use aliases ?

### ISSUE THREAD

**Issue by inredmood** [dpress29/libmail#1]
Salut !
J’ai commencé à tester un peu libmail. J’aime beaucoup, par contre je me demandais s’il est possible de définir des alias. J’ai créé des identités, je peux envoyer des mails sous différentes identités, mais le destinataire ne peut pas me répondre, à moins que toutes mes identités aient la même adresse, que mon adresse principale.

**Comment by dpress29** [comment]
salut !
merci à toi pour ton retour positif.
Effectivement je n'ai pas prévu la possibilité de créer un alias dans le formulaire d'inscription, néanmoins il y a possibilité d'en faire (j'ai conçu la BDD de telle sorte que ce soit possible à l'avenir) ce qu'il me manque c'est le temps.
Actuellement je suis en train de bosser sur un projet bien plus gros [Elukerio](https://www.elukerio.org), [libmail.eu](https://www.libmail.eu) est intégré dedans. Il y a aura un panel complet de gestion qui réunira tous les services (mail, nextcloud, peertube ...), il y aura une nouvelle infra (fini le petit VPS, et place à un serveur Bull avec Xéon 16 coeurs et 32 Go de RAM).
Si tu as vraiment besoin de la fonctionnalité, je suis pas contre un petit pull request. Sinon exceptionnellement je peux te faire un alias manuellement si tu me contactes par mail. elukerio[at]libmail[dot]eu

**Comment by inredmood** [comment]
Gros projet, ça sonne très intéressant.
Je serais pas capable de proposer un pull request, je maîtrise à peine les bases en php et ça fais très longtemps que j’en fais plus, je suis de la team python :) Mais de toute façon, j’ai pas d’urgence là-dessus, je peux patienter.
